### ISSUE TITLE
Rankings Dependent on Team Ordering

### ISSUE THREAD

**Issue by lilleswing** [jbadlato/Markov-Rankings#202]
https://github.com/jbadlato/Markov-Rankings/blob/414c770d9567dc9dd1f27928b05ee911caa2b48e/app/scripts/calculateRankings.ts#L169-L185

** My Thoughts Not Verfied **

I'm pretty sure the rankings will be dependent on whichever team is indexed at the 0 location.
This also has bad repercussions for for the diagonal. That is team[0] playing themselves.

Assumptions
-------------------------
The scores matrix is only filled with absolute value of loosing scores.  You ignore wins when filling out the team matrix.  That is you can interpret the matrix as the probability of team[column] beating team[row]

Take the pathological case of one team dominating the rest of the league.  It's row besides the diagonal will be very "full".  That causes the fill in for the diagonal to be very small.  If this team happens to be team[0], it will under represent the strength of team[0].

Fixes
-------------------------
Teams should be ranked on the sum of the column ignoring elements of the diagonal.
```python
column_sums = np.sum(scoreMatrix, axis=0)
for i in range(len(column_sums)):
  column_sums[i] -= scoreMatrix[i][i]
```
this can then go into your loop on line 178.

**Comment by jbadlato** [comment]
So if I'm understanding everything you said correctly, kind of.  At this point in the code, `scoresMatrix` isn't exactly scores anymore (yes, plenty of refactoring/renaming needed in this code :smiley:).  The matrix at this point is after the Markov chain/random walk simulation has been run (i.e. the matrix has been multiplied by itself iteratively until all the rows converge to the same value).  So, at this point, all the rows are the same - ideally.

Where the trouble can come from is:

1. the tolerance of how we measure the rows are "equal" is too large (notice my TODO on line 162 - been meaning to come up with a more reasonable end condition than comparing the first element in the first two rows - not exactly robust.)
2. the graph isn't well connected (i.e. early in the season before enough games are played) - in this case only rows within the well connected sub-graphs are equal to each other (at least I think...I'm not 100% sure - but I am quite certain that the rows will never all be the equal)

In those two cases, the rankings are absolutely affected by the order of the teams.  Otherwise, it shouldn't matter, since all rows converge to the same values as the Markov chain/random walk progresses to infinity.

# General Explanation
So to clear up how these rankings are calculated overall:

Think of the probability matrix as a graph, with each node representing a team.  Then imagine a (not-very-loyal) fan who will embark on a random walk through this graph.  If the fan is on node i, the fan is currently a fan of team i.  At each step of the random walk, the fan watches all of team i's games, and decides if they are still a fan of team i, or if they now think another team is better.  Each edge originating from node i represents the probability the fan will jump ship from team i and become a fan of team j.  

If we wanted to find the probability that this person is a fan of team x after 2 steps of the random walk, we can just take the square of the probability matrix.  After 3 steps, cube the matrix, and so on.  As we approach infinity, it quickly becomes insignificant which team the fan started with (i.e. the row in the matrix).  Thus, we can interpret the probabilities as ratings of each team.

Here are the steps in the code:
1. Scores Matrix is created: the value at (i, j) is the number of points that team i has scored against team j throughout the season (it sounds like this differs from your first assumption)
2. Scores Matrix is transformed into a probability matrix.  The transformation steps are:
   * transpose matrix - fairly self explanatory. The way I originally construct the scores matrix is so team i's score against team j is in (i,j).  So the edge in the graph from team i to team j (which represents fans leaving team i in favor of team j) should be weighted heavier the more points team i allows team j to score on them. (it sounds like this is where your second assumption differs - the transpose means that later on, the diagonal will end up large for a team dominating the league)
    * Divide all elements in the matrix by the sum of all elements - since we want probabilities between 0 and 1, we need to normalize the matrix over all the scores.  In all honesty, I forget if there's anything special about using the sum of all elements, other than guaranteeing that every value will be less than 1.  It seems intuitive enough though.
   * Set the diagonal element (i,i) equal to 1 - sum of all the elements in row i.  Each row needs to add up to 1, since each row represents a complete set of all possible outcomes of the next step in the random walk.
3. Probability Matrix is raised to the "infinity" power - really just multiplied by itself until an arbitrary end condition is reached.
4.  At this point, all rows in the probability matrix are (approximately) equal - so we take an arbitrary row and treat the ith value as the rating of team i.  The highest rating is the # 1 team, next highest is # 2, and so on.
